FROM alpine:3.12

LABEL description="Alpine Linux with clang-format v10"
LABEL maintainer="Moritz Kiehn <msmk@cern.ch>"
# increase whenever any of the RUN commands change
LABEL version="1"

RUN apk add --no-cache clang
